# Generated by Django 4.1.3 on 2022-12-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lottery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moment",
                    models.CharField(
                        choices=[
                            ("mañana", "mañana"),
                            ("tarde", "tarde"),
                            ("noche", "noche"),
                        ],
                        default="mañana",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10000)),
                ("summary", models.TextField(blank=True)),
                ("featured", models.BooleanField(default=True)),
            ],
        ),
    ]
