# Generated by Django 4.1.3 on 2022-12-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_lottery_date_lottery_numbers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lottery", old_name="numbers", new_name="numbers_afternoon",
        ),
        migrations.RemoveField(model_name="lottery", name="moment",),
        migrations.AddField(
            model_name="lottery",
            name="numbers_night",
            field=models.JSONField(default=list),
        ),
    ]
